sudo: required
services:
  - docker
before_install:
  - chmod -R 777 *
script:
  - export TAG1=$DOCKER_USER/app-store:$TRAVIS_BUILD_NUMBER
  - export TAG2=$DOCKER_USER/app-store:latest
  - docker build --compress --tag=$TAG1 --tag=$TAG2 --file=docker/Dockerfile .
after_success:
  - docker login --username $DOCKER_USER --password $DOCKER_PASS
  - if [[ $TRAVIS_BRANCH == "master" && $TRAVIS_PULL_REQUEST == "false" ]]; then 
      docker push $TAG1; 
      docker push $TAG2; 
    fi
